### ISSUE TITLE
reCaptcha reset

### ISSUE THREAD

**Issue by danieljausovec** [slushie/recaptcha-secure-token#3]
Hi.

reCaptcha after jQuery reset no longer work.
I get "Bad request" from google.

Example:
grecaptcha.reset();

**Comment by slushie** [comment]
I cannot reproduce this issue on my own. However, the ReCaptcha stoken has a built-in timestamp value. It's possible that you are calling "reset" with an expired stoken. You should re-generate your stoken before calling "reset."

I'm going to close the issue for now, unless you can provide repeatable steps to reproduce.
