### ISSUE TITLE
Secure token timestamp

### ISSUE THREAD

**Issue by mtilburg** [slushie/recaptcha-secure-token#4]
Hello,

I found some strange behaviour of the widget.
Casting round(microtime(true)*1000) to a int gives error: stoken expired error.
Just returning the rounded value works fine. Hope it helps someone.

Tested on Windows Server 2012 with PHP 5.3.19

Kind regards,

Marc van Tilburg

protected function currentTimestamp() {
    return round(microtime(true)*1000);
    //return intval(round(microtime(true) \* 1000)); //intval makes it invalid?
}

**Comment by slushie** [comment]
What an interesting bug...

The "[official](https://github.com/google/recaptcha-java/blob/master/appengine/src/main/java/com/google/recaptcha/STokenUtils.java#L39)" implementation uses Java's `System.currentTimeMillis()` which returns an integral type `long`. 

I did a bit of testing locally on PHP 5.6.11, `json_encode()` treats floats with zero precision (ie, no digits after the decimal point) exactly the same as integers. That is, `json_encode(['ts_ms' => 1.0]) === json_encode(['ts_ms' => 1])`.

I'm currently unable to test on Windows, but a [cursory test](https://3v4l.org/XBX5U) indicates the same holds true for all supported PHP versions, at least on *nix. However, the Windows system clock is notoriously imprecise. 

Is your Windows version 32-bit? It may be that `intval()` is overflowing PHP's integer type on 32-bit systems. In which case, it would be safest to leave the value as a `float` and let `json_encode()` handle the conversion (by definition, JSON types are unbounded). 

Can you please confirm you are on a 32-bit system? Also, is the output of `round(microtime(true) * 1000) > PHP_INT_MAX` true? If so, I will update my code to return a float from `currentTimestamp()`.

**Comment by mtilburg** [comment]
Hello Slushie,

I am running PHP x86 (32 bit) on a 64 bit Windows 2012 server.
Casting microtime(true)*1000 to int definitely overflows PHP_INT_MAX on a 32 bit PHP version.

PHP_INT_MAX = 2147483647
round(microtime(true)_1000) = float 1444202997088
intval(round(microtime(true)_1000)) = int 1093985632

Kind regards,
Marc van Tilburg

**Comment by slushie** [comment]
Hi
I just published a new version (1.1.1) with float timestamps. You should be able to do `php composer update` and get the latest version, which should fix this bug.

Cheers!
